on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: build with pyinstaller
      run: |
        pyinstaller --onefile ts3-mute-bot.py
        
    - name: Create Release
      id: create_release
      uses: "marvinpinto/action-automatic-releases@latest"
      
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "master"
        prerelease: true
        title: "Development Build"
        files: |
          LICENSE.txt
          config.json
          /dist/ts3-mute-bot.exe
