on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: /

    - uses: actions/upload-artifact@v2
      with:
        name: main.exe
        path: /dist/
